#"/bin/sh

apm install Hydrogen
apm install Sublime-Style-Column-Selection
apm install ask-stack
apm install atom-beautify
apm install atom-django
apm install atom-material-syntax
apm install atom-material-ui
apm install atom-python-run
apm install auto-detect-indentation
apm install autocomplete-json
apm install autocomplete-paths
apm install autocomplete-python
apm install busy-signal
apm install emmet
apm install file-icons
apm install git-plus
apm install highlight-selected
apm install intentions
apm install language-liquid
apm install linter
apm install linter-csslint
apm install linter-htmlhint
apm install linter-jshint
apm install linter-pylama
apm install linter-ui-default
apm install markdown-preview-plus
apm install minimap
apm install pane-layout-plus
apm install pigments
apm install platformio-ide-terminal
