version: "3"
services:
  jupyter_local:
    container_name: jupyter_local
    build:
      context: jupyter
    env_file:
      - .env
    ports:
      - 8888:8888
    volumes:
      - ./jupyter:/code
      - ./data:/mnt/data

  postgres_local:
    container_name: postgres_local
    build:
      context: .
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./data:/mnt/data
    env_file:
      - .env
    ports:
      - 5432:5432

  http_local:
    container_name: http_local
    build:
      context: http
    volumes:
      - ./data:/mnt/data
    env_file:
      - .env
    ports:
      - 80:80